
# Numpy Arrays

In [6]:
my_list = [1,2,3]

In [9]:
import numpy as np

In [10]:
arr = np.array(my_list)

In [11]:
arr

array([1, 2, 3])

In [12]:
my_mat = [[1,2,3] , [4,5,6] , [7,8,9]]

In [13]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(0)

array([], dtype=float64)

In [17]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [18]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [20]:
np.linspace(0,5,100)

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [21]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [23]:
np.random.rand(5,5)

array([[ 0.54303519,  0.60655576,  0.75892997,  0.6766881 ,  0.11451135],
       [ 0.33924544,  0.49103534,  0.39266335,  0.03482635,  0.53106498],
       [ 0.13759859,  0.57622987,  0.39380122,  0.13432445,  0.98751701],
       [ 0.0175945 ,  0.46845381,  0.10520108,  0.42076155,  0.9469349 ],
       [ 0.40149326,  0.02093178,  0.55965698,  0.8419111 ,  0.1519865 ]])

In [25]:
np.random.randn(4,4)

array([[-2.26543506,  0.3061362 , -0.62719559,  0.17135771],
       [-0.34712139, -1.05015906,  0.19335129, -2.91980648],
       [ 0.73937499, -2.62882422, -1.73942527,  1.36240924],
       [ 0.42528117, -1.4661581 , -0.07886076,  0.51828221]])

In [54]:
np.random.randint(1,100,10)

array([57, 58, 63,  9, 59,  2, 87, 53, 22, 26])

In [56]:
arr = np.arange(25)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
ranarr = np.random.randint(0,50,10)

In [60]:
ranarr

array([40, 27, 20, 26, 36, 17, 48, 32, 48, 21])

In [62]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
ranarr.max()

48

In [66]:
ranarr.min()

17

In [67]:
arr.shape

(25,)

In [68]:
arr = arr.reshape(5,5)

In [69]:
arr.shape


(5, 5)

In [70]:
arr.dtype

dtype('int32')